import { bilingual as b, type Text } from './domain-config';
export interface Resource {
  id: string;
  title: Text;
  author: Text;
  description: Text;
  type: 'book' | 'blog' | 'official' | 'learning';
  language: string;
  url: string;
  categories: string[];
  pathwayIds?: string[];
  courseIds?: string[];
  careerIds?: string[];
  japan?: boolean;
  pdfPage?: number;
}
export const resources: Resource[] = [
  {
    id: 'optexpert',
    title: b('OptExpert', 'اپت‌اکسپرت'),
    author: b('OptExpert', 'اپت‌اکسپرت'),
    description: b(
      'Courses and practical material for operations research and optimization.',
      'دوره‌ها و محتوای کاربردی برای تحقیق در عملیات و بهینه‌سازی.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://optexpert.org/',
    categories: ['math'],
    pathwayIds: ['optimization', 'logistics'],
    courseIds: ['ise-109', 'ise-110'],
  },
  {
    id: 'optexpert-optimization-modeling',
    title: b('Optimization Modeling', 'مدل‌سازی بهینه‌سازی'),
    author: b('OptExpert', 'اپت‌اکسپرت'),
    description: b(
      'A focused course on formulating and implementing optimization models.',
      'دوره‌ای متمرکز بر صورت‌بندی و پیاده‌سازی مدل‌های بهینه‌سازی.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://optexpert.org/courses/optimization-modeling/',
    categories: ['math'],
    pathwayIds: ['optimization', 'logistics'],
    courseIds: ['ise-109', 'ise-110'],
  },
  {
    id: 'pyomo-channel',
    title: b('Pyomo Learning Channel', 'کانال آموزشی Pyomo'),
    author: b('Telegram', 'تلگرام'),
    description: b(
      'Learning material for optimization modeling with Python and Pyomo.',
      'محتوای آموزشی مدل‌سازی بهینه‌سازی با پایتون و Pyomo.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://t.me/pyomochannel',
    categories: ['math', 'programming'],
    pathwayIds: ['optimization', 'logistics'],
    courseIds: ['ise-109', 'ise-110'],
  },
  {
    id: 'optexpert-vrp-python',
    title: b(
      'Vehicle Routing Problems with Python',
      'مسئله مسیریابی وسایل نقلیه با پایتون',
    ),
    author: b('OptExpert', 'اپت‌اکسپرت'),
    description: b(
      'A practical course on vehicle routing models and Python implementation.',
      'دوره‌ای کاربردی درباره مدل‌های مسیریابی وسایل نقلیه و پیاده‌سازی با پایتون.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://optexpert.org/courses/vrp-python/',
    categories: ['core', 'programming'],
    pathwayIds: ['logistics'],
    courseIds: ['ise-138'],
  },
  {
    id: 'optexpert-health-optimization',
    title: b('Healthcare Optimization', 'بهینه‌سازی در سلامت'),
    author: b('OptExpert', 'اپت‌اکسپرت'),
    description: b(
      'Applied optimization concepts and models for healthcare systems.',
      'مفاهیم و مدل‌های کاربردی بهینه‌سازی برای سیستم‌های سلامت.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://optexpert.org/courses/health-opt/',
    categories: ['other'],
    pathwayIds: ['healthcare'],
    courseIds: ['health-001'],
  },
  {
    id: 'pouriya-baghdadi',
    title: b('Data Analytics Learning Channel', 'کانال آموزشی تحلیل داده'),
    author: b('Pouriya Baghdadi · Telegram', 'پوریا بغدادی · تلگرام'),
    description: b(
      'Persian learning material for data analytics and business intelligence.',
      'محتوای آموزشی فارسی برای تحلیل داده و هوش تجاری.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://t.me/pouriyabaghdadi',
    categories: ['programming'],
    pathwayIds: ['data-ai'],
    careerIds: ['data-analytics', 'business-intelligence'],
  },
  {
    id: 'tahlilgary',
    title: b('Tahlilgary', 'تحلیلگری'),
    author: b('Tahlilgary', 'تحلیلگری'),
    description: b(
      'Persian courses and articles for data analysis and business intelligence.',
      'دوره‌ها و مقاله‌های فارسی در زمینه تحلیل داده و هوش تجاری.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://www.tahlilgary.com/',
    categories: ['programming'],
    pathwayIds: ['data-ai'],
    careerIds: ['data-analytics', 'business-intelligence'],
  },
  {
    id: 'bahmani-class360',
    title: b('Industrial Engineering · Class 360', 'مهندسی صنایع · کلاس ۳۶۰'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian learning resource for the Industrial Engineering career path.',
      'منبع آموزشی فارسی برای مسیر شغلی مهندسی صنایع.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/mr-class360',
    categories: ['core'],
    pathwayIds: ['optimization'],
    careerIds: ['industrial-engineer'],
  },
  {
    id: 'bahmani-alfa-msp-2',
    title: b('Alfa MSP 2', 'آلفا MSP ۲'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'Project-control training centered on Microsoft Project workflows.',
      'آموزش کنترل پروژه با تمرکز بر گردش کار Microsoft Project.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/alfa-msp-2',
    categories: ['management'],
    pathwayIds: ['optimization', 'finance'],
    careerIds: ['project-control'],
  },
  {
    id: 'bahmani-alfa-msp',
    title: b('Alfa MSP', 'آلفا MSP'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian Microsoft Project course for project planning and control.',
      'دوره فارسی Microsoft Project برای برنامه‌ریزی و کنترل پروژه.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/alfa-msp',
    categories: ['management'],
    pathwayIds: ['optimization', 'finance'],
    careerIds: ['project-control'],
  },
  {
    id: 'bahmani-god-of-project',
    title: b('God of Project', 'خدای پروژه'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A broader Persian learning program for project management and control.',
      'برنامه آموزشی جامع‌تر برای مدیریت و کنترل پروژه.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/god-of-project',
    categories: ['management'],
    pathwayIds: ['optimization', 'finance'],
    careerIds: ['project-control'],
  },
  {
    id: 'bahmani-work-study',
    title: b('Work Study', 'کارسنجی و زمان‌سنجی'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian course on work measurement, method study, and productivity.',
      'دوره فارسی درباره اندازه‌گیری کار، روش‌سنجی و بهره‌وری.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/work-study',
    categories: ['core'],
    pathwayIds: ['optimization', 'hse'],
    courseIds: ['ise-105'],
  },
  {
    id: 'bahmani-production-planning',
    title: b('Production Planning', 'برنامه‌ریزی تولید'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian learning resource for production planning and control roles.',
      'منبع آموزشی فارسی برای نقش‌های برنامه‌ریزی و کنترل تولید.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/mr-tolid',
    categories: ['core'],
    pathwayIds: ['logistics'],
    careerIds: ['production-planning'],
  },
  {
    id: 'bahmani-iso',
    title: b('ISO and Standards', 'ISO و استانداردها'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian learning resource for ISO standards and management systems.',
      'منبع آموزشی فارسی برای استانداردهای ISO و سیستم‌های مدیریتی.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/mr-iso-01',
    categories: ['management', 'core'],
    pathwayIds: ['quality'],
    careerIds: ['iso-standards'],
  },
  {
    id: 'bahmani-quality-assurance',
    title: b('Quality Assurance', 'تضمین کیفیت'),
    author: b('Bahmani IE', 'بهمنی صنایع'),
    description: b(
      'A Persian learning resource for quality-assurance systems and practice.',
      'منبع آموزشی فارسی برای سیستم‌ها و فعالیت‌های تضمین کیفیت.',
    ),
    type: 'learning',
    language: 'fa',
    url: 'https://bahmaniie.ir/master-qa',
    categories: ['core'],
    pathwayIds: ['quality'],
    careerIds: ['quality-assurance'],
  },
  {
    id: 'python-book',
    title: b('Python for Data Analysis', 'پایتون برای تحلیل داده'),
    author: b('Wes McKinney · 3rd edition', 'وس مک‌کینی · ویرایش سوم'),
    description: b(
      'An open-access guide to working with data using Python and pandas. Listed in the curriculum’s BI reading list.',
      'راهنمای دسترسی آزاد کار با داده در پایتون و pandas؛ معرفی‌شده در فهرست منابع درس هوشمندی کسب‌وکار.',
    ),
    type: 'book',
    language: 'en',
    url: 'https://wesmckinney.com/book/',
    categories: ['programming'],
    pdfPage: 128,
  },
  {
    id: 'warehouse-book',
    title: b('The Data Warehouse Toolkit', 'ابزارهای انبار داده'),
    author: b(
      'Ralph Kimball & Margy Ross · 3rd edition',
      'رالف کیمبال و مارگی راس · ویرایش سوم',
    ),
    description: b(
      'Understand dimensional modeling and the structure behind business intelligence systems.',
      'شناخت مدل‌سازی بُعدی و ساختار زیربنایی سیستم‌های هوش تجاری.',
    ),
    type: 'book',
    language: 'en',
    url: 'https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/books/data-warehouse-dw-toolkit/',
    categories: ['programming'],
    pdfPage: 128,
  },
  {
    id: 'persian-quality',
    title: b(
      'Statistical Quality Control — Persian reference',
      'کنترل کیفیت آماری',
    ),
    author: b(
      'Douglas Montgomery · translated by Rasoul Noorossana',
      'داگلاس مونتگومری · ترجمه رسول نورالسنا',
    ),
    description: b(
      'A Persian reading recommendation for statistical quality control. Open the curriculum bibliography for the supplied reference.',
      'منبع فارسی پیشنهادی کنترل کیفیت آماری؛ برای مشخصات ارجاع، فهرست منابع برنامه درسی را ببینید.',
    ),
    type: 'book',
    language: 'fa',
    url: '/curriculum-1403.pdf#page=53',
    categories: ['core', 'math'],
    pdfPage: 53,
  },
  {
    id: 'persian-or',
    title: b(
      'Introduction to Operations Research — Persian reference',
      'آشنایی با تحقیق در عملیات',
    ),
    author: b(
      'Hamdy Taha · translated by Mohammad Bagher Bazargan',
      'حمدی طه · ترجمه محمدباقر بازرگان',
    ),
    description: b(
      'A Persian operations research reference listed in the national curriculum. The link opens its bibliography, not a book download.',
      'منبع فارسی تحقیق در عملیات معرفی‌شده در برنامه درسی؛ پیوند، فهرست منابع را باز می‌کند و فایل کتاب نیست.',
    ),
    type: 'book',
    language: 'fa',
    url: '/curriculum-1403.pdf#page=57',
    categories: ['math'],
    pdfPage: 57,
  },
  {
    id: 'iise-bok',
    title: b('ISE Body of Knowledge', 'پیکره دانش مهندسی صنایع و سیستم‌ها'),
    author: b(
      'Institute of Industrial & Systems Engineers',
      'مؤسسه مهندسان صنایع و سیستم‌ها',
    ),
    description: b(
      'A professional map of the field’s knowledge areas, useful for seeing how your courses fit together.',
      'نقشه حرفه‌ای حوزه‌های دانش رشته برای شناخت ارتباط میان درس‌ها.',
    ),
    type: 'official',
    language: 'en',
    url: 'https://www.iise.org/Details.aspx?id=43631',
    categories: ['core', 'management'],
  },
  {
    id: 'curriculum',
    title: b('Undergraduate Curriculum · 1403', 'برنامه درسی کارشناسی · ۱۴۰۳'),
    author: b(
      'Ministry of Science, Research and Technology',
      'وزارت علوم، تحقیقات و فناوری',
    ),
    description: b(
      'The supplied national curriculum with syllabi, prerequisites and reading lists. This site retains the Excel catalog as its organizing source.',
      'برنامه درسی ارائه‌شده شامل سرفصل‌ها، پیش‌نیازها و منابع؛ مبنای سازمان‌دهی فهرست این سایت همچنان کاربرگ اکسل است.',
    ),
    type: 'official',
    language: 'fa',
    url: '/curriculum-1403.pdf',
    categories: [],
  },
  {
    id: 'toyota-tps',
    title: b('Toyota Production System', 'سیستم تولید تویوتا'),
    author: b('Toyota Motor Corporation', 'شرکت تویوتا'),
    description: b(
      'See how Just-in-Time and jidoka connect production flow, inventory and quality. Read the explanation from Toyota itself.',
      'ارتباط تولید به‌موقع و جیدوکا با جریان تولید، موجودی و کیفیت را در توضیح رسمی تویوتا بخوانید.',
    ),
    type: 'official',
    language: 'en',
    url: 'https://global.toyota/en/company/vision-and-philosophy/production-system/',
    categories: ['core', 'management'],
    japan: true,
  },
  {
    id: 'toyota-tour',
    title: b('Inside Toyota’s Production System', 'درون سیستم تولید تویوتا'),
    author: b('Toyota · Virtual Plant Tour', 'تویوتا · بازدید مجازی کارخانه'),
    description: b(
      'Follow practical examples of flow and problem detection, then connect them to your production and quality courses.',
      'نمونه‌های عملی جریان کار و تشخیص مسئله را دنبال کنید و به دروس تولید و کیفیت پیوند دهید.',
    ),
    type: 'learning',
    language: 'en',
    url: 'https://global.toyota/en/company/plant-tours/production-system/',
    categories: ['core'],
    japan: true,
  },
  {
    id: 'lean-post',
    title: b('The Lean Post', 'لین پست'),
    author: b('Lean Enterprise Institute', 'مؤسسه لین'),
    description: b(
      'Practitioner articles about lean thinking, leadership and continuous improvement.',
      'مقاله‌های فعالان حرفه‌ای درباره تفکر ناب، رهبری و بهبود مستمر.',
    ),
    type: 'blog',
    language: 'en',
    url: 'https://www.lean.org/the-lean-post/articles/',
    categories: ['core', 'management'],
    japan: true,
  },
  {
    id: 'mit-linear',
    title: b('Linear Algebra · OpenCourseWare', 'جبر خطی · آموزش آزاد MIT'),
    author: b('MIT · Gilbert Strang', 'MIT · گیلبرت استرنگ'),
    description: b(
      'Lectures and exercises on vectors, matrices and linear systems to strengthen your mathematical foundation.',
      'درس‌گفتار و تمرین درباره بردار، ماتریس و دستگاه خطی برای تقویت پایه ریاضی.',
    ),
    type: 'learning',
    language: 'en',
    url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    categories: ['math'],
  },
  {
    id: 'ortools',
    title: b('Optimization with OR-Tools', 'بهینه‌سازی با OR-Tools'),
    author: b('Google for Developers', 'گوگل برای توسعه‌دهندگان'),
    description: b(
      'Official examples for routing, scheduling and mathematical optimization.',
      'نمونه‌های رسمی مسیریابی، زمان‌بندی و بهینه‌سازی ریاضی.',
    ),
    type: 'learning',
    language: 'en',
    url: 'https://developers.google.com/optimization',
    categories: ['math', 'programming'],
  },
  {
    id: 'python-tutorial',
    title: b('The Python Tutorial', 'آموزش پایتون'),
    author: b('Python Software Foundation', 'بنیاد نرم‌افزار پایتون'),
    description: b(
      'Start with the official language tutorial and practice the building blocks of programming.',
      'از آموزش رسمی زبان شروع کنید و مبانی برنامه‌نویسی را تمرین کنید.',
    ),
    type: 'learning',
    language: 'en',
    url: 'https://docs.python.org/3/tutorial/',
    categories: ['programming'],
  },
  {
    id: 'comfar',
    title: b('COMFAR & Investment Appraisal', 'COMFAR و ارزیابی سرمایه‌گذاری'),
    author: b('UNIDO', 'سازمان توسعه صنعتی ملل متحد'),
    description: b(
      'Connect engineering economy to financial and economic appraisal of industrial projects.',
      'پیوند اقتصاد مهندسی با ارزیابی مالی و اقتصادی طرح‌های صنعتی.',
    ),
    type: 'official',
    language: 'en',
    url: 'https://www.unido.org/comfar',
    categories: ['finance'],
  },
  {
    id: 'nist',
    title: b('Engineering Statistics Handbook', 'راهنمای آمار مهندسی'),
    author: b('NIST / SEMATECH', 'NIST / SEMATECH'),
    description: b(
      'A technical reference for measurement, statistical methods and process improvement.',
      'مرجع فنی اندازه‌گیری، روش‌های آماری و بهبود فرایند.',
    ),
    type: 'learning',
    language: 'en',
    url: 'https://www.itl.nist.gov/div898/handbook/',
    categories: ['math', 'core', 'other'],
  },
];

export const resourcesForCourse = (courseId: string) =>
  resources.filter((resource) => resource.courseIds?.includes(courseId));

export const resourcesForCareer = (careerId: string) =>
  resources.filter((resource) => resource.careerIds?.includes(careerId));
